### ISSUE TITLE
Create UML - Activity Diagram

### ISSUE THREAD

**Issue by levtmadden** [OrientDN-InternalProjects/2023SEInternSS1-book-store-api#3]

**Comment by Dat070601** [comment]
Hello @levtmadden 
Please Take a look at our Activity Diagram

Due to screen problem on Large size diagram that can't be shrunk, we will provide the diagram drive link for you to enter and take a look at it https://drive.google.com/file/d/1l6L4VCtxA2BhrSAkUQbXJ4drsxlTjqdi/view?usp=sharing, please download the diagram file
and import to draw.io.

Thank you.
